name: Compile LaTeX

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        working-directory: codebook
        run: |
          mkdir -p .build
          # albatross 这 
          xelatex -interaction=nonstopmode -output-directory=.build codebook.tex
          
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: .build/codebook.pdf
