name: Build Codebook

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile with latexmk
        working-directory: codebook
        run: |
          mkdir -p .build
          latexmk -xelatex -interaction=nonstopmode -output-directory=.build codebook.tex
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: codebook
          path: codebook/.build/codebook.pdf
